Metaswitch/crest

- docs/Bulk-Provisioning Numbers.md
- src/metaswitch/crest/tools/sstable_provisioning/README.md
Ellie, I finally got round to merging the memento bulk provisioning changes. This PR contains the corresponding docs changes. Please can you review?
> [Reviewer: Ellie] Update docs to cover memento bulk provisioning

- docs/development.md
Update development docs with homestead-prov changes
> [No reviewer] Docs

- src/metaswitch/crest/main.py
Fixes #192.
Tested by:
* killing with SIGABRT, checking that it comes back to life, and that I see this log:
```
2015-02-12 11:14:22,371 UTC WARNING main:68 UNIX socket /tmp/.homer-sock-0 exists, but lock /tmp/.homer-sock-0.lockfile is not held - deleting stale /tmp/.homer-sock-0
2015-02-12 11:14:22,372 UTC INFO main:71 Going to listen for HTTP on UNIX socket /tmp/.homer-sock-0
```
* killing normally (with 'service homer stop') and checking that it comes back to life and doesn't warn about stale sockets.
Although I didn't explicitly set out to test this, it looks like we tried to start multiple conflicting Homers at one point and it didn't cause chaos:
```
$ pgrep -lf homer
9396 poll_homer.sh
9399 /bin/sh /etc/monit/run_logged /etc/init.d/homer start
9400 /bin/sh /etc/monit/run_logged …
```
> [Reviewer: Matt] Safely remove any stale UNIX socket before trying to bind to it

- homer.monit
- homer.root/usr/share/clearwater/bin/poll_homer.sh
- homestead-prov.monit
- homestead.root/usr/share/clearwater/bin/poll_homestead-prov.sh
Homer/Homestead-prov changes (following template of https://github.com/Metaswitch/chronos/pull/107)
> [Reviewer: Matt] Monit changes

- src/metaswitch/crest/tools/sstable_provisioning/ClearwaterBulkProvisioner.java
- src/metaswitch/crest/tools/sstable_provisioning/README.md
Andy,
Please can you review this enhancement to speed up bulk-provisioning.  With this approach, I can get 1M subscribers provisioned for stress testing in less than 3 minutes.
Matt
> [Reviewer: Andy] Faster bulk provisioning using command-line arguments

- homer.root/etc/cron.hourly/homer-log-cleanup
- homestead.root/etc/cron.hourly/homestead-prov-log-cleanup
- src/metaswitch/crest/main.py
- src/metaswitch/crest/tools/create_db.py
- src/metaswitch/crest/tools/stresstool.py
Basically identical to Ellis PR #102.
> [No review needed] Update python common

- homer.monit
- homestead-prov.monit
Metaswitch/clearwater-monit#16
> [No reviewer] Add in groups

- homer.root/usr/share/clearwater/clearwater-cluster-manager/plugins/homer_cassandra_plugin.py
> [No reviewer] GR-aware Cassandra plugin

- debian/homer.postinst
- homer.root/usr/share/clearwater/infrastructure/scripts/create-homer-nginx-config
- homestead.root/usr/share/clearwater/infrastructure/scripts/create-homestead-prov-nginx-config
> Reviewer Ellie - Enable homer site in infrastructure

- buildout.cfg
Add Mock as an egg. 
Fixes #209. 
Tested live
> [Reviewer: Andy] Add mock as an egg

- homer.root/usr/share/clearwater/clearwater-cluster-manager/plugins/homer_cassandra_plugin.py
Co-req change to accompany https://github.com/Metaswitch/clearwater-etcd/pull/70
> [Reviewer: Andy] Enable cassandra clustering to cope with multiple networks

- src/metaswitch/crest/api/base.py
- src/metaswitch/crest/api/homestead/backends/hss/__init__.py
- src/metaswitch/crest/api/homestead/provisioning/models.py
- src/metaswitch/crest/api/statistics.py
- src/metaswitch/crest/main.py
- src/metaswitch/crest/test/__init__.py
- src/metaswitch/crest/test/api/base.py
- src/metaswitch/crest/tools/bulk_autocomplete.py
- src/metaswitch/crest/tools/bulk_create.py
- src/metaswitch/crest/tools/utils.py
Fix up make verify warnings for crest
> [Reviewer: Rob] Make verify fixes

- docs/homestead_prov_api.md
- src/metaswitch/crest/api/homestead/provisioning/handlers/irs.py
- src/metaswitch/crest/api/homestead/provisioning/handlers/private.py
- src/metaswitch/crest/api/homestead/provisioning/handlers/service_profile.py
This wraps the delete attempts in a try and catches any NotFoundExceptions. Tested live
Fixes #226
> [Reviewer: Rob] Wrap delete attempts in try/excepts

- docs/Bulk-Provisioning Numbers.md
- docs/homestead_prov_api.md
- homestead.root/usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh
- src/metaswitch/crest/api/homestead/provisioning/handlers/private.py
- src/metaswitch/crest/api/homestead/provisioning/models.py
- src/metaswitch/crest/test/api/homestead/provisioning/__init__.py
- src/metaswitch/crest/test/api/homestead/provisioning/handlers/__init__.py
- src/metaswitch/crest/test/api/homestead/provisioning/handlers/private.py
- src/metaswitch/crest/tools/bulk_create.py
- src/metaswitch/crest/tools/sstable_provisioning/ClearwaterBulkProvisioner.java
- src/metaswitch/crest/tools/sstable_provisioning/README.md
- src/metaswitch/crest/tools/sstable_provisioning/prepare_csv.py
Rob, can you review this change to support storing the plaintext password for a subscriber.
> [Reviewer: Rob] Sto1416

- homer.root/usr/share/clearwater/infrastructure/scripts/homer
- homestead.root/usr/share/clearwater/infrastructure/scripts/create-homestead-prov-nginx-config
- homestead.root/usr/share/clearwater/infrastructure/scripts/homestead-prov
Similar fix to https://github.com/Metaswitch/crest/pull/229
> [No reviewer] Check for config before running scripts

- src/metaswitch/crest/api/homestead/provisioning/handlers/public.py
Rob, please can you review this PR that fixes #252? Tested live by:
* Creating one subscriber and checking that `wget http://localhost:8889/public/` gave a complete json document. 
* Adding another subscriber and re-running the same test.
> [Reviewer: Rob] Write a space before each sleep to avoid timing out connections

- homer.root/usr/share/clearwater/cassandra-schemas/homer.sh
- homestead.root/usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh
Fix schema creation for https://github.com/Metaswitch/clearwater-cassandra/issues/54
> [No reviewer] Fix up schema creatioN

- docs/development.md
Add creating the homestead_cache keyspace to the crest docs
> [Reviewer: Rob] Add cache commands

- homer.root/usr/share/clearwater/infrastructure/scripts/homer
- homestead.root/usr/share/clearwater/infrastructure/scripts/homestead-prov
Same as https://github.com/Metaswitch/homestead/pull/270.
> [Reviewer: Ellie] Check that Cassandra is installed before installing schema

- src/metaswitch/homer/validator.py
Remove an unused import that fails "make verify" and breaks CI.
> Remove unused import

- .gitignore
- Makefile
- debian/crest.install
- docs/development.md
- mk/bulk-provision.mk
- src/metaswitch/crest/tools/sstable_provisioning/Makefile
- src/metaswitch/crest/tools/sstable_provisioning/README.md
- src/metaswitch/crest/tools/sstable_provisioning/prepare_csv.py
Matt, can you review this change to build the java bulk provision tool and include it in crest installs?
Tested live
Fixes #267
> [Reviewer: Matt] Build the bulk provisioning tools

- setup_crest.py
Pin third party code to a known version
> [No reviewer] Add explicit version constraints

- Makefile
Same 'fix' as for https://github.com/Metaswitch/python-common/pull/51
> [No reviewer] Fail on coverage

- debian/homer.postinst
- debian/homestead-prov.postinst
Same as https://github.com/Metaswitch/ellis/pull/180.
> [No review required] Use --always-unzip when installing eggs

- Makefile
This works for me, but could you test this branch locally as well?
> [Reviewer: Ellie] Always install setuptools 24 - 25 doesn't like being installed by easy_install

- docs/Bulk-Provisioning Numbers.md
- src/metaswitch/crest/tools/stress_provision.sh
You mentioned it at lunch one day, I had a bit of free time, the rest is history.
> [Reviewer: Graeme] Add one single bulk provisioning command

- homestead-prov-cassandra.root/usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh
This fixes are the homestead-prov equivalents of the fixes to https://github.com/Metaswitch/homestead/issues/396 and https://github.com/Metaswitch/homestead/issues/333
> [Reviewer: Ellie] homestead-prov upgrade warning logs

- src/metaswitch/homer/tools/migrate_tool.py
> [No reviewer] Remove unnecessary global

- src/metaswitch/crest/api/ping.py
This PR handles the deferred exception in the ping handler so that it doesn't spam the logs with exceptions
Tested live. Fixes #313 and fixes #297
> [Reviewer: Seb] Catch deferred exceptions in ping handler

- debian/homer.init.d
- debian/homestead-prov.init.d
Linked to:
https://github.com/Metaswitch/crest/issues/305
https://github.com/Metaswitch/sprout/issues/1326
https://github.com/Metaswitch/clearwater-monit/pull/47
> [No reviewer] Have init scripts remove the pidfile if abort command fails

- homer-cassandra.root/usr/share/clearwater/cassandra-schemas/homer.sh
- homestead-prov-cassandra.root/usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh
Connect to the local cassandra when creating schemas
(https://github.com/Metaswitch/clearwater-issues/issues/2152)
> [No reviewer] Cassandra schema creation

- homer.monit
- homestead.root/usr/share/clearwater/infrastructure/scripts/homestead-prov.monit
As per https://github.com/Metaswitch/sprout/pull/1863
> [No reviewer] Don't wait for 6 cycles before killing a process

- Makefile
https://github.com/Metaswitch/clearwater-etcd/pull/473
> Run Bandit analysis from python.mk as part of build process

- homestead-prov-cassandra.root/usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh
No need to have alter commands anymore.
Tested live.
> [Reviewer: Sathiyan] Dead code - remove schema changes

- debian/crest.postinst
As per https://github.com/Metaswitch/clearwater-etcd/pull/493
> [No reviewer] Install later version of pip and wheel

- debian/crest-prov.postinst
Mirrors crest.postinst - https://github.com/Metaswitch/crest/blob/dev/debian/crest.postinst#L41
> [No reviewer] Clear out the venv as well to pip upgrade issue

- crest-requirements.txt
> [Reviewer: Krista] Add missing pin for six

- .gitignore
- Makefile
- debian/crest-prov.install
- debian/crest.install
- debian/homer.install
- debian/homestead-prov.install
Use the new common python build infrastructure in https://github.com/Metaswitch/clearwater-build-infra/pull/69
> Common build infra

- src/metaswitch/homestead_prov/cassandra.py
- src/metaswitch/homestead_prov/provisioning/models.py
- src/metaswitch/homestead_prov/test/cache/cache.py
> Revert "[Reviewer: EM] Set consistency level of reads and writes to quorum"

- Makefile
Match https://github.com/Metaswitch/ellis/pull/223
> [No reviewer] Only rebuild the common wheel if it's been cleaned

- src/metaswitch/homestead_prov/cassandra.py
- src/metaswitch/homestead_prov/provisioning/models.py
- src/metaswitch/homestead_prov/test/cache/cache.py
> [No reviewer] Set consistency level of reads and writes to quorum

- Makefile
- debian/crest-prov.install
- debian/crest.install
- debian/homer.install
- debian/homestead-prov.install
See https://github.com/Metaswitch/clearwater-build-infra/pull/76
> [No reviewer] Updates for changes to python build infra
