docs/development.md, homestead.local_settings/local_settings.py
Matt, please could you review this change for https://github.com/Metaswitch/clearwater-snmp-handlers/issues/36. It changes the name of the unix domain socket that homestead-prov uses for stats from `homestead` (which conflicts with the homestead process) to `homestead-prov`. This doesn't completely fix the issue, but it makes it less severe. 
Tested as follows. Stats were retrieved using the command `snmpwalk -v2c -c clearwater homestead-1.ajh.cw-ngv.com 1.2.826.0.1.1578918.9`
* Initial install, stats returned. **Failed** (due to https://github.com/Metaswitch/clearwater-snmp-handlers/issues/37)
* Restart SNMP, stats returned. Passed.
* Restart homestead, stats returned. Passed.
* Restart homestead-prov, stats returned. Passed.
* Reboot node, stats returned. Passed.
* Start a second …
=> [Reviewer: Matt] Move homestead-prov to it's own unix domain socket

debian/homer.init.d, debian/homestead-prov.init.d
Andy,
Please can you review my enhancement to add a `service ... run` option to run a service blocking (i.e. not as a daemon)?  Most of the changes are refactoring so that run and start can share the same code.
This has been tested live.
Thanks,
Matt
=> [Reviewer: Andy] Add service run command to run blocking

src/metaswitch/crest/tools/sstable_provisioning/ClearwaterBulkProvisioner.java
I spotted that the homestead_provisioning keyspace wasn't being provisioned, because it tries to reuse an iterator. I don't think there's a good way to reset an iterator in Java, so I've just created a second one for the second keyspace.
=> [Reviewer: Matt] Fix homestead_provisioning bulk provisioning

debian/homestead-prov.postinst, homestead.root/usr/share/clearwater/infrastructure/scripts/create-homestead-prov-nginx-config
Enable the homestead-prov site in clearwater infra rather than at install time so we can learn shared config late.
=> Reviewer Ellie - Set up sites-enabled in infrastructure script

homer.root/usr/share/clearwater/infrastructure/scripts/create-homer-nginx-config, homestead.root/usr/share/clearwater/infrastructure/scripts/create-homestead-prov-nginx-config
This means that we'll catch the case where the symlink is missing (i.e. the site's not enabled) since `diff` returns 2 in the case that one of it's specified files can't be opened.
=> Reviewer Graeme - Diff against the symlink, not the main file

README.md, docs/homer_api.md, docs/homestead_prov_api.md
We had a mailing list question about it, so I thought the `/ping` URL should be in the API docs.
=> [Reviewer: Ellie] Document the /ping endpoint

homer.root/usr/share/clearwater/infrastructure/scripts/create-homer-nginx-config, homer.root/usr/share/clearwater/infrastructure/scripts/homer
This changes means the scripts only set up the local_settings file and nginx config if sufficient configuration is available. Homer will cyclically reboot until these files have been created. 
This is a partial fix for the general issue in #224, if this is OK I'll make the same changes to the other repos.
=> [Reviewer: Rob] Check config is available

src/metaswitch/crest/api/homestead/cache/db.py
Ellie,
Please can you review this?  (One aspect of #223.)  Basically, we had log spam from a trace that was error-level, but should have been much lower.  Investigating further, it looks like this was intended to troubleshoot a specific issue that is now resolved, so I've removed it entirely.
Matt
=> [Reviewer: Ellie] Remove debugging trace statement that is now spammy

src/metaswitch/crest/api/base.py, src/metaswitch/crest/api/lastvaluecache.py, src/metaswitch/crest/main.py
Ellie,
Please can you review this?  (One aspect of #223.)
Previously, on `service homestead-prov stop` we caught the `SIGTERM` but didn't shut down ZMQ, so the Twisted reactor still kept running and we waited until the `SIGKILL` to terminate.  Now, we honor the `SIGTERM` and tidy up ZMQ, and hence close the whole process down.
Tested live.
Thanks,
Matt
=> [Reviewer: Ellie] Unbind ZMQ when shutting down to ensure clean termination

src/metaswitch/crest/api/base.py, src/metaswitch/crest/test/api/base.py
Ellie,
Please can you review this fix to #226.  We might choose to change the return code, but I think this fix is correct anyway - it *never* makes sense to return a body with a 204 response.
Tested live, as well as with the UT below.
Matt
=> [Reviewer: Ellie] Don't return a body with a 204 response

docs/homestead_prov_api.md, src/metaswitch/crest/api/homestead/__init__.py, src/metaswitch/crest/api/homestead/provisioning/handlers/public.py, src/metaswitch/crest/api/homestead/provisioning/models.py
Should be mostly unsurprising - you've seen the design. The only new thing of note is that you can specify `?fast=true` to not return service profile and implicit registration set UUIDs, which can be an order of magnitude faster; I might not keep this option available permanently, but I'd at least like to have it for my perf testing, so  can compare the two options.
I've tested with 10k subscribers, confirming that I get 10,000 results on a GET and that it's slower and less CPU-intensive with `?chunk-proportion=16`.
=> [Reviewer: Ellie] Add a /public/ API for querying all SIP URIs

docs/homestead_prov_api.md, src/metaswitch/crest/api/homestead/provisioning/handlers/public.py
Rob,
Please can you review my enhancement to the bulk retrieval API to allow the chunk size to be specified by the client, rather than being timed by the server?
No UT because we don't have a good infrastructure on this part of the API, but live-tested.
Changes to clearwater-prov-tools to use this API will follow shortly.
Matt
=> [Reviewer: Rob] Add chunking to bulk retrieval API

src/metaswitch/crest/api/homestead/provisioning/models.py
Fixes https://github.com/Metaswitch/crest/issues/249. Tested live:
```
[homestead-1]ubuntu@ec2-54-208-206-129:~$ /usr/share/clearwater/bin/create_user 3 rkd.cw-ngv.com hi
Public User ID sip:3@rkd.cw-ngv.com:
Private User ID 3@rkd.cw-ngv.com:
HA1 digest: a43efb3d960016725c3c86b0debfc1fd
iFC:
<?xml version="1.0" ?>
<ServiceProfile>
</ServiceProfile>
[homestead-1]ubuntu@ec2-54-208-206-129:~$ /usr/share/clearwater/bin/list_users
sip:3@rkd.cw-ngv.com
[homestead-1]ubuntu@ec2-54-208-206-129:~$ /usr/share/clearwater/bin/delete_user 3 rkd.cw-ngv.com
[homestead-1]ubuntu@ec2-54-208-206-129:~$ /usr/share/clearwater/bin/list_users
[homestead-1]ubuntu@ec2-54-208-206-129:~$
```
I haven't perf-tested - I think even if it had a perf impact, we'd want to merge it.
=> [Reviewer: Ellie] Don't list deleted users

src/metaswitch/crest/api/homestead/provisioning/handlers/public.py
This is to avoid slowing down the `list_users` command. This adaptively changes the chunk-proprtion it requests, and sleeping for a second on each request dramatically slows this down when there are small numbers of subscribers. 
Effectively a revert of https://github.com/Metaswitch/crest/commit/8ba57744b93128b2be4dba992b5d7af14e788c80, but with some extra commenting.
=> [No review required] Don't sleep unecessarily when listing all subscribers

debian/homer.init.d, debian/homestead-prov.init.d, setup.py, src/metaswitch/crest/main.py
Homer and homestead-prov's init.d script uses only the executable name to identify homer and homestead-prov functions.  This causes problems if another script (e.g. a bulk import) is being run using the homer or homestead-prov python interpreter at the same time as the daemon is started or stopped.  For starting, start-stop-daemon will refuse to start it, and for stopping it will kill the bulk import script.
The fix is to use the process name to identify the daemon processes, which we can set using the `prctl` system call.
This also has the advantage that the daemons appear as `homer` and `homestead-prov` in process management tools like `top`.
=> Use process name to identify homer and homestead-prov

homestead.root/usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh
Hi Ellie, 
This is a fix for some spurious error messages that are produced when run on a split network system.
I've tested this on our deployment, please could you review? It has a corresponding Homestead fix that I'll link once the PR is created.
Cheers,
Tom
=> [Reviewer: Ellie] Run cqlsh in correct namespace

docs/development.md, src/metaswitch/homestead_prov/auth_vectors.py, src/metaswitch/homestead_prov/cache/cache.py, src/metaswitch/homestead_prov/cache/db.py, src/metaswitch/homestead_prov/provisioning/models.py, src/metaswitch/homestead_prov/test/cache/cache.py
Rob,
Please can you review this change to remove the unused preferred flag from AV (equivalent to https://github.com/Metaswitch/homestead/pull/310, but for crest)?
I've run UTs.
Matt
=> [Reviewer: Rob] Remove (unused) preferred flag from AV

docs/development.md, setup_crest.py, setup_homer.py, setup_homestead_prov.py, src/metaswitch/crest/api/base.py, src/metaswitch/crest/api/statistics.py, src/metaswitch/crest/test/api/base.py
Use the PyPI mononotonic module.
Instead of using our own code to get monotonic time, use the publicly
available monotonic module to do so.
This follows on from the changes in https://github.com/Metaswitch/python-common/pull/48.
=> [Reviewer Matt] Monotonic

homer.root/usr/share/clearwater/cassandra-schemas/homer.sh, homer.root/usr/share/clearwater/infrastructure/scripts/homer, homestead.root/usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh, homestead.root/usr/share/clearwater/infrastructure/scripts/homestead-prov
As suggested in https://github.com/Metaswitch/homestead/issues/269, moves the "is Cassandra installed" check into the schema scripts.
* I've changed the check to be more explicit about dpkg states - there's a half-installed state that I was worried the old grep might catch
* I've read the docs to convince myself that we'll never end up in a state where we don't get the schemas installed - although a package might be unpacked before its dependencies are configured, it will always be configured after its dependencies are configured, so when homer.postinst runs and calls `/usr/share/clearwater/cassandra-schemas/homer.sh`, the dpkg-query check must return true at that point and the rest of the code will run
* Just in case this does cause issues, I've added a log so we can detect problems from …
=> [Reviewer: Ellie] Bail out of schema scripts if Cassandra is not installed

homer.root/usr/share/clearwater/bin/poll_homer.sh
Same as https://github.com/Metaswitch/clearwater-infrastructure/pull/332, but for this repo.
=> Switch from Python version of bracket_ipv6_address to C++ version

src/metaswitch/crest/api/ping.py, src/metaswitch/crest/test/api/ping.py
This aims to fix issue #283 by restarting Homer if Cassandra requests aren't getting responses.
I've tested this live on an aio image, both using curl to check the behaviour of the poll, and watching monit summary to see that monit does the right thing.
=> [Reviewer Ellie] Enhance ping to do a Cassandra request

src/metaswitch/crest/api/ping.py, src/metaswitch/crest/test/api/ping.py
I forgot that `make test` doesn't run all the tests. This fixes up coverage, and some test bugs.
- Make sure to use the right mocks for the right job.
- Use a DeferredList rather than gatherResults to ensure that all
requests complete.
- Use the 'fail' convenience method to fail.
=> [Reviewer: Ellie] Fix up tests.

src/metaswitch/crest/api/ping.py
This tweaks the change made in #287 so that it doesn't consume all errors (which masks the case when Cassandra is down).
Fixes #283 
Testing has been on a Homer node and I've checked that killing cassandra causes monit to restart Homer and starting Homer without a running cassandra process causes monit to restart Homer
=> [Reviewer: Rob] Don't consume all errors

debian/homer.init.d, debian/homestead-prov.init.d, src/metaswitch/crest/main.py, src/metaswitch/crest/settings.py
Pass the log level in via the command line so it's configured from /etc/clearwater rather than local_settings.py
This fixes issue #290 and issue #272.
I've tested this on a homer node, configuring the log level via `/etc/clearwater/user_settings`, and then running `sudo monit restart homer_process`.
After this, I need to fix up the docs which claim all sorts of things - e.g. that log_level 1 is error logs only (it's warnings as well), or how you log from crest, which just doesn't work at all.
=> [Reviewer: Ellie] Configure logging via user_settings

src/metaswitch/crest/tools/sstable_provisioning/README.md
Hey Rob,
I've tried the changes we discussed, running the process from the home directory, but this led to the step where you run Bulkprovision throwing some more errors. 
I think the simplest 'fix' is to have users chown the directory at the start. It also keeps the file paths in the commands simple.
This works, and i think is better than just making the folder writable by all? (i.e. chmod 777) But shout if you think this might cause other problems, if the root user later needs to do anything in this folder or anything like that.
I've also made a couple of minor fixes, adding `-g` to the monit commands, and fixing `plaintext_parameter` to `plaintext_password`.
=> [Reviewer: Rob] Fix unwritable directory issue, and minor other fixups

debian/homer-cassandra.install, src/metaswitch/crest/tools/sstable_provisioning/README.md
Stop `homer-cassandra` owning the paths `/usr/share/clearwater/crest/src/metaswitch/crest/` and `/usr/share/clearwater/crest/tools/sstable_provisioning`.
This means that when we have both homestead-prov-cassandra and homer-cassandra installed, we no longer have problems where both of those packages try to own the paths above.
I've made some changes to the sstable documentation, where I removed all references to homer, but I don't know about sstable so they might be wrong.
=> [Reviewer: RKD] Move all provisioning scripts to homestead-prov-cassandra

debian/homer.init.d, debian/homestead-prov.init.d
This is needed because currently if only one of homer or homestead-prov are running, `sudo service [homer|homestead-prov] status` always reports that bother processes are running. This is because $NAME is just used for the output, and there's no way to distinguish between them.
=> Reviewer EM: Use pidfile in status call

src/metaswitch/crest/api/ping.py, src/metaswitch/crest/test/api/ping.py, src/metaswitch/homer/__init__.py, src/metaswitch/homestead_prov/__init__.py, src/metaswitch/homestead_prov/cassandra.py
Hi Ellie, please could you review this fix to #283 which reworks the ping handler so that it can check homestead-prov's connection to cassandra as well as homer's. I've tested this live as follows:
* Stopped cassandra. Homer and homestead-prov restart periodically. 
* Started casssandra. Homer and homestead-prov start up and stay running.
=> [Reviewer: Ellie] Make the ping handler also check homestead's connection to cassandra

src/metaswitch/crest/tools/stress_provision.sh
I ran the new bulk_prov script, and it gave me this output:
```
Generating bulk provisioning scripts for users in /tmp/26656.users.csv...
Generated homestead bulk provisioning scripts
- /tmp/26656.users.create_homestead.sh           - run this script on Homestead
- /tmp/26656.users.create_homestead_cache.casscli - copy this file onto Homestea                                                                             d
- /tmp/26656.users.create_homestead_provisioning.casscli - copy this file onto H                                                                             omestead
Generated homer bulk provisioning scripts
- /tmp/26656.users.create_xdm.sh                 - run this script on Homer
- /tmp/26656.users.create_xdm.cqlsh              - copy this file onto Homer
Created 50000 …
```
=> [Reviewer: RKD] Hide confusing output

docs/development.md
The apt python-virtualenv package installs virtualenv 1.11.4. This is not up to date enough for our builds.
This instead uses pip to install the latest virtualenv package. At time of testing, this pulled down 15.1.0. The version in use on a number of machines is 13.1.0. 
@eleanor-merry Do you think we should pin to 13.1.0? The builds work with the latest version, but if the install command doesn't specify a version, it will not upgrade to a new version if someone has already installed the apt package.
=> [Reviewer: Ellie] Install up to date virtualenv

src/metaswitch/crest/api/base.py, src/metaswitch/crest/test/api/base.py
Since we only use the accepted_percent for logging, just set it to 100 if we
don't have any stats for it.
Also adds a UT for this case
Fixes #301
=> [Reviewer: Ellie] Don't attempt to divide by zero

setup_crest.py
Tested live on EC2, this gets things alive again. Fixes #325 
We should do a proper investigation of what things we depend on, and consider version pinning more. In the process of tracking this down, I also saw that twisted has updated, and in testing that i also had to specifically pin setuptools=24 in setup_crest.py (not sure why, but install failed without this).
However, this PR is just MVP for unblocking everything.
@sebrexmetaswitch this should have been built by the morning, so you should be good to go
=> [No reviewer] Pin to thrift 0.9.3, as it updated to 0.10.0

src/metaswitch/crest/api/base.py, src/metaswitch/crest/test/api/base.py
This came out of investigating #244 . As Chris suggested there, increasing the size of the bucket is the simplest resolution; i've upped it to 100 for now, with an initial rate of 100, but i'd like to discuss what you think actual reasonable values for the token rates etc. would be.
While investigating, i saw that as long as the latency was good, the token rate would increase every 20 requests, with no upper limit, so i've ported over the function already present in https://github.com/Metaswitch/cpp-common/blob/master/src/load_monitor.cpp#L85 to give us a min_threshold of accepted requests relative to the rate for us to qualify for rate increase.
Tested live, by running `while true; do curl -v "http://hs.ajl.cw-ngv.com:8889/private/2345550154%40ajl.cw-ngv.com/associated_public_ids" && …
=> [Reviewer: Ellie] Better load monitor. In line with cpp monitoring

debian/homer.init.d, debian/homestead-prov.init.d
Yeah. So my changes in https://github.com/Metaswitch/crest/pull/331 just meant that they would murder-cycle forever. 
This should have them properly check the working directory of the 'leaked' pids they find, and only kill things that match their DAEMON_DIR.
Tested live, and resolves issue https://github.com/Metaswitch/crest/issues/333 , so i'm pretty sure this is good. Still worth a review though. 
Going to go through the other init file changes i made to make sure there aren't any other possible process deathmatches going on
=> [Reviewer: Graeme] Stop murder circle

debian/control, debian/crest.postinst, debian/homestead-prov.postinst
Two fixes to the way we build and install crest.
One fixes missing build dependencies - we require cassandra and a Java JDK to build the sstable provisioning tool - https://github.com/Metaswitch/crest/tree/dev/src/metaswitch/crest/tools/sstable_provisioning
Secondly, remove a requirement for config to be setup at package installation time.
=> [Reviewer: Seb] Build and install fixes

debian/homestead-prov-cassandra.install, debian/homestead-prov-cassandra.postinst
Installs the crest eggs as part of the homestead-prov-cassandra debian package so that the provisioning scripts will work wherever this package is installed.
Tested that this fixed the issue I saw.
=> [Reviewer: EM] Fix up provisioning scripts

src/metaswitch/crest/tools/bulk_create.py, src/metaswitch/crest/tools/sstable_provisioning/ClearwaterBulkProvisioner.java, src/metaswitch/crest/tools/sstable_provisioning/prepare_csv.py
Now that we've added support for this field, it breaks registrations since Homestead-prov returns iFCs that have no unbarred URIs.
=> [Reviewer: EM] Remove BarringIndication field from provisioning scripts

src/metaswitch/crest/api/ping.py, src/metaswitch/homestead_prov/cassandra.py
Seb,
This adds IPv6 support to Homestead Prov.
It's fairly simple, and I've tested both on a VMWare deployment using IPv6 and a Chef deployment using IPv4.
I've also added some useful logging - debug only, so disabled by default, so shouldn't be a problem.
(There's a slightly awkward land mine that the debug log line saying how we are connecting to Cassandra is not emitted even when debug logging is enabled because we don't enable logging until after we've connected to Cassandra...)
=> [Reviewer: Seb] IPv6 Support Homestead Provisioning

src/metaswitch/homestead_prov/cassandra.py
As discussed, this should address the blank Cassandra hostname issue.
I've run all of the UTs, but I don't have an AIO to test the actual issue on.
=> [Reviewer: Seb] Handle blank cassandra_hostname

debian/homestead-prov.prerm
Currently removing homestead-prov erroneously deletes all of the monit files. This fixes that to just remove the one we want to remove.
=> [Reviewer: Seb] Fix monit file deletion

setup_crest.py
Move cryptography later in the list so that we can actually build crest with
cryptography 2.0 available.
This works because easy_install installs dependencies in reverse order
=> [Reviewer: Seb] Resolve building with cryptography

Makefile, debian/.gitignore, setup_crest.py
Follow on from https://github.com/Metaswitch/crest/pull/353, but this time https://pypi.python.org/pypi/idna has been updated.
As previously discussed, this isn't the correct fix due to how fragile it is.
=> [Reviewer: Seb] Resolve crest build failure with updated IDNA

Makefile, setup_crest.py
Seb,
This all gets worse.
pycparser (used by python-common) is also used by cryptography.
When you run `${ENV_DIR}/bin/easy_install -zmaxd .crest-eggs/ .crest-eggs/*.egg` it installs the eggs in alphabetical order. Thus it picks up crest -> cryptography -> pycparser first, and then common -> pycparser second. The later is pinned to 2.7, but crytography doesn't pin pycparser.
Oddly the install works in the Debian build, but fails in the Debian install - which shouldn't happen.
This fixes it so we install the dependencies for python-common first, and then the dependencies for crest.
=> [Reviewer: Seb] Install metaswitch-common dependencies prior to crest

homer-cassandra.root/usr/share/clearwater/cassandra-schemas/homer.sh, homestead-prov-cassandra.root/usr/share/clearwater/cassandra-schemas/homestead_provisioning.sh
This adds a return code to adding the schemas so we can retry if it fails. It also moves the Homer schema script to have the same format as the homestead-prov schema script.
Tested live.
=> [Reviewer: Krista] Get return code from cassandra schemas

Makefile
Seb,
Most of our Python based repos store their eggs by default in a `.eggs` directory.
Crest doesn't, as it has three packages - so it has `.crest-eggs`, `.homer-eggs`, `.homestead_prov-eggs`. The Bandit exclusion list incorrectly excludes `.eggs`.
This only causes a problem if you build the Debian with `make deb` prior to running `make analysis` and without running `make clean` in between.
I've tested by running `make deb` and then `make analysis` and this passes correctly.
=> [Reviewer: Seb] Correctly ignore egg files in analysis

Makefile
This partially reverts an earlier change (https://github.com/Metaswitch/crest/commit/fa7265ccbc2a938a263e979beb938401d8e1205c) - we also need to ignore the .eggs folder as it's used by Python.
=> [Reviewer: Adam] Re-add .eggs folder

homer-cassandra.root/usr/share/clearwater/cassandra/users/homer, homestead-prov-cassandra.root/usr/share/clearwater/cassandra/users/homestead-prov
This is the co-requisite change to use the common infrastructure to enable Cassandra as per https://github.com/Metaswitch/clearwater-infrastructure/pull/486
=> [Reviewer: Adam] Add scripts to enable Cassandra for Homer and Homestead Prov

Makefile
Ensure we have an up to date version of pip with wheel support to avoid:
```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: invalid command 'bdist_wheel'
```
=> [No reviewer] Upgrade pip

src/metaswitch/homestead_prov/cassandra.py, src/metaswitch/homestead_prov/provisioning/models.py, src/metaswitch/homestead_prov/test/cache/cache.py
Sets the consistency level of reads and writes to Cassandra to quorum. This fixes the issue where we could successfully write to Cassandra and then fail to read back the data immediately afterwards.
=> [Reviewer: EM] Set consistency level of reads and writes to quorum

src/metaswitch/crest/api/passthrough.py, src/metaswitch/homestead_prov/cassandra.py, src/metaswitch/homestead_prov/provisioning/models.py
This changes the cassandra behaviour to do a local quorum read/write, and fall back to a one read/write if there's an unavailable exception.
Tested live, and all the existing UTs pass (I'm intending to add more, but I'd like to fix the master build).
=> [Reviewer: Sathiyan] Fix up HA gets

crest-requirements.txt, homer.local_settings/local_settings.py, homestead.local_settings/local_settings.py, setup_crest.py, src/metaswitch/crest/api/xsd.py, src/metaswitch/crest/tools/bulk_create.py, src/metaswitch/crest/tools/utils.py, src/metaswitch/homestead_prov/provisioning/handlers/service_profile.py, src/metaswitch/homestead_prov/provisioning/models.py
No lxml parse change as there is no equivalent XMLParser in defusedxml, and I don't have any other particularly good ideas for what to do instead! However, I'm reasonably sure that xsd.py file is only used by Homer, which is Project Clearwater only.
=> Bandit final
